name: Sharkcomm
favicon: null
layout_spectrum: 0.5866349672432989
typography_spectrum: 0.42529623094014823
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.5419774721376598
  lightness: 0.6630056011490524
  saturation: 0.047501802910119295
  rhythmicContrast: 0.1635245664510876
purpose: []
