name: Sharkcomm
favicon: null
layout_spectrum: 0.16872
typography_spectrum: 0.42529623094014823
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#98b7ff'
    - '#526497'
    - '#2d3858'
    - '#04050d'
    - '#768fd5'
  brandStrength: 0.8125
  lightness: 0.6630056011490524
  saturation: 0.0625
  rhythmicContrast: 0.1635245664510876
purpose: []
