typography_spectrum: 0.42529623094014823
color:
  brandColors:
    - '#98b7ff'
    - '#526497'
    - '#2d3858'
    - '#04050d'
    - '#768fd5'
  brandStrength: 0.8125
  lightness: 0.6630056011490524
  saturation: 0.0625
  rhythmicContrast: 0.1635245664510876
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Sharkcomm
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Welcome to Shark.
description: Branding / Marketing / Web / Digital
purpose: []
